### ISSUE TITLE
Screenshot in README

### ISSUE THREAD

**Issue by curran** [yosiasz/d3-chords#1]
Currently, folks need to go through the whole installation process to see what this looks like. It would be great to have a screenshot of the end product in the README, like this project does https://github.com/sul-cidr/josquin-ribbon .

**Comment by yosiasz** [comment]
Done! Thank you

**Comment by curran** [comment]
Nice! Now it's clear that it's about *guitar* chords, not chords in general. Nice work, looks super cool.
